### ISSUE TITLE
Unknown Chain ID when running yarn fund-cchain-addresses

### ISSUE THREAD

**Issue by Astrovicis** [ava-labs/avalanche-smart-contract-quickstart#11]
Upon running yarn fund-cchain-addresses, I receive the following:

```
yarn run v1.22.10
warning ../../../../../package.json: No license field
$ npx hardhat run scripts/fund-cchain-addresses.js
Exporting 1000 AVAX to each address on the C-Chain...
Error: Error returned: {"jsonrpc":"2.0","error":{"code":-32000,"message":"unknown chain ID","data":null},"id":4}
    at /Users/me/Desktop/Programming/place/otherplace/avalanche-smart-contract-quickstart/node_modules/src/common/jrpcapi.ts:55:19
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at main (/Users/me/Desktop/Programming/place/otherplace/avalanche-smart-contract-quickstart/scripts/fund-cchain-addresses.js:129:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Halp.

**Comment by visopsys** [comment]
I got the same problem too. Do I need to run Avalanche node or avash before running this script?

**Comment by visopsys** [comment]
Seems like you need to run avash and create some nodes.

```
avash
runscript scripts/five_node_staking.lua
```

**Comment by visopsys** [comment]
@Astrovicis I think the of C-chain ID in the AvalancheJS repo is out of sync with the one on AvalancheGo. In the `fund-cchain-address.js` file, try replacing cChainBlockchainID value. It works for me

```
// const cChainBlockchainID = utils_1.Defaults.network['12345'].C.blockchainID;
const cChainBlockchainID = '2XFHbWN57HrjHW1JqhP9wzj92eYHpiH7EGLnY9mNfWn9w9CvWR';
```

**Comment by cgcardona** [comment]
AvalancheJS should have the [correct C-Chain ID](https://github.com/ava-labs/avalanchejs/blob/0a73aee8c550098579b8c5c9e6ec029cdbb971dd/src/utils/constants.ts#L304)

Can you confirm that you're using avalanchejs v3.2.5?

**Comment by cgcardona** [comment]
Did this work?

**Comment by visopsys** [comment]
@cgcardona I pulled everything again (avalanchego, avash and this repo). The  avalanchejs versions is `3.2.0` as specified in the package.json of this repo. 

I no longer see `unknown chain ID` error but got this new error `tx outputs not sorted`:

```
Exporting 1000 AVAX to each address on the C-Chain...
RVRVy7dvJ7qjBFpQbpeqdmSgJqPudtkYxsSbZtc4Sp1rUBbUJ
Importing AVAX to the C-Chain...
(node:23879) UnhandledPromiseRejectionWarning: Error: Error returned: {"jsonrpc":"2.0","error":{"code":-32000,"message":"tx outputs not sorted","data":null},"id":2}
    at /Users/billy/Desktop/code/crypto-projects/avalanche-smart-contract-quickstart/node_modules/src/common/jrpcapi.ts:55:19
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at main (/Users/billy/Desktop/code/crypto-projects/avalanche-smart-contract-quickstart/scripts/fund-cchain-addresses.js:133:21)
(node:23879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cgcardona** [comment]
You need to use the latest version of [avalanchego](https://github.com/ava-labs/avalanchego/releases/tag/v1.3.2) and [avalanchejs](https://github.com/ava-labs/avalanchejs/releases/tag/v3.2.6)

**Comment by cgcardona** [comment]
Any luck?

**Comment by yesil** [comment]
I encountered the same issue and after updating it worked.
I think would be nice to bump the version in package.json.

**Comment by tuangu** [comment]
I had the same issue (unkown chain ID) with master branch, even after trying to upgrade the avalanchejs to 3.2.6 (as suggested above). With the latest avalanchejs (3.5.1), I got a different error:
```
yarn run v1.22.10
$ npx hardhat run scripts/fund-cchain-addresses.js
/home/tuan/crypto/avalanche-smart-contract-quickstart/node_modules/avalanche/src/utils/index.ts:1
export * from './base58';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tuan/crypto/avalanche-smart-contract-quickstart/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/tuan/crypto/avalanche-smart-contract-quickstart/node_modules/src/apis/socket/socket.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
error Command failed with exit code 1.
```
My environment:
avalanche/1.4.7 [network=mainnet, database=v1.4.5, commit=e0e562eb54a0609db4afd997184a3e4d23a5ea7f]
avash commit: 35b64847b371e5a14cb48ca817726d298d3e06ca

**Comment by paOol** [comment]
this is resolved in https://github.com/ava-labs/avalanche-smart-contract-quickstart/pull/22
