### ISSUE TITLE
Error: problem parsing address 'X-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u': expected hrp "custom" but got "local"

### ISSUE THREAD

**Issue by billyjacoby** [ava-labs/avalanche-smart-contract-quickstart#32]
When trying to run through the tutorial I get this error when trying to run `fund-cchain-addresses`

**Comment by techyhippy** [comment]
I got exactly the same error.. here it is in full... please help! 

```
$ yarn fund-cchain-addresses
yarn run v1.22.17
$ npx hardhat run scripts/fund-cchain-addresses.js
Error: problem parsing address 'X-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u': couldn't parse address "X-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u": expected hrp "custom" but got "local"
    at AVMAPI.<anonymous> (/test/avalanche-smart-contract-quickstart/node_modules/src/common/jrpcapi.ts:68:15)
    at Generator.next (<anonymous>)
    at fulfilled (/test/avalanche-smart-contract-quickstart/node_modules/avalanche/dist/common/jrpcapi.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mengvisal** [comment]
Yeah I am having the same issue. Is this solved yet?

**Comment by japina** [comment]
The same issue here. On Mac (if it is relevant).
