### ISSUE TITLE
Refund script doesn't work properly on local network

### ISSUE THREAD

**Issue by legkvla** [ava-labs/avalanche-smart-contract-quickstart#41]
I tried to follow your manual https://docs.avax.network/dapps/smart-contracts/using-hardhat-with-the-avalanche-c-chain

this part works fine:
```
yarn accounts --network local
yarn balances --network local
```

and got stuck with:
```
yarn fund-cchain-addresses --network local
```

Got such errors:

Error - Base58.decode: not a valid base58 string
Exporting 1000 AVAX to each address on the C-Chain...
Error: problem decoding transaction: missing 0x prefix to hex encoding
    at AVMAPI.<anonymous> (/Users/apple/dev/smartcontracts/avalanche-smart-contract-quickstart/node_modules/src/common/jrpcapi.ts:68:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/apple/dev/smartcontracts/avalanche-smart-contract-quickstart/node_modules/avalanche/dist/common/jrpcapi.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by maishivamhoo123** [comment]
@team can you please assign this issue to me ?
